com.liferay.portal\:com.liferay.portal.kernel\:2.23.0=\
	com/liferay/portal/kernel/exception/NoSuchSubscription*,\
	com/liferay/portal/kernel/model/Subscription*,\
	com/liferay/portal/kernel/service/Subscription*,\
	com/liferay/portal/kernel/service/persistence/Susbscription*,\
	com/liferay/portal/kernel/util/comparator/Subscription*