com.liferay.portal\:com.liferay.portal.impl\:2.11.0=\
	com/liferay/portal/model/impl/Subscription*,\
	com/liferay/portal/service/base/Subscription*,\
	com/liferay/portal/service/impl/Subscription*,\
	com/liferay/portal/service/persistence/impl/Subscription*
